package com.server.glol.domain.match.dto

import com.server.glol.domain.match.dto.riot.matchv5.ParticipantDto

data class MatchInfoDto(
    val totalMinionsKilled: Int = 0,
    val kills: Int = 0,
    val assists: Int = 0,
    val deaths: Int = 0,
    val teamPosition: String = "",
    val teamId: Int = 0,
    val win: Boolean = false,
    val wardsPlaced: Int = 0,
    val wardsKilled: Int = 0,
    val controlWardsPlaced: Int = 0,
    val totalDamageDealtToChampions: Int = 0,
    val item0: Int = 0,
    val item1: Int = 0,
    val item2: Int = 0,
    val item3: Int = 0,
    val item4: Int = 0,
    val item5: Int = 0,
    val item6: Int = 0,
    val championName: String = "",
    val championId: Int = 0,
    val championLevel: Int = 0,
    val name: String = "",
    val firstSummonerSpell: Int = 0,
    val secondSummonerSpell: Int = 0,
) {
    constructor(dto: ParticipantDto): this(
        dto.totalMinionsKilled,
        dto.kills,
        dto.assists,
        dto.deaths,
        dto.teamPosition,
        dto.teamId,
        dto.win,
        dto.wardsPlaced,
        dto.wardsKilled,
        dto.wardsPlaced,
        dto.totalDamageDealtToChampions,
        dto.item0,
        dto.item1,
        dto.item2,
        dto.item3,
        dto.item4,
        dto.item5,
        dto.item6,
        dto.championName,
        dto.championId,
        dto.champLevel,
        dto.summonerName,
        dto.summoner1Id,
        dto.summoner2Id,
    )
}