package com.server.glol.domain.match.dto

import com.server.glol.domain.match.dto.riot.matchv5.ParticipantDto

data class MatchInfoDto(
    val totalMinionsKilled: Int,
    val kills: Int,
    val assists: Int,
    val deaths: Int,
    val teamPosition: String,
    val teamId: Int,
    val win: Boolean,
    val wardsPlaced: Int,
    val wardsKilled: Int,
    val controlWardsPlaced: Int,
    val totalDamageDealtToChampions: Int,
    val item0: Int,
    val item1: Int,
    val item2: Int,
    val item3: Int,
    val item4: Int,
    val item5: Int,
    val item6: Int,
    val championName: String,
    val championId: Int,
    val championLevel: Int,
    val name: String,
    val firstSummonerSpell: Int,
    val secondSummonerSpell: Int,
) {
    constructor(dto: ParticipantDto): this(
        dto.totalMinionsKilled,
        dto.kills,
        dto.assists,
        dto.deaths,
        dto.teamPosition,
        dto.teamId,
        dto.win,
        dto.wardsPlaced,
        dto.wardsKilled,
        dto.wardsPlaced,
        dto.totalDamageDealtToChampions,
        dto.item0,
        dto.item1,
        dto.item2,
        dto.item3,
        dto.item4,
        dto.item5,
        dto.item6,
        dto.championName,
        dto.championId,
        dto.champLevel,
        dto.summonerName,
        dto.summoner1Id,
        dto.summoner2Id,
    )
}