package com.server.glol.domain.match.dto

import com.server.glol.domain.match.dto.riot.matchv5.ParticipantDto

data class MatchDetailDto(
    val matchId: String = "",
    val queueId: String = "",
    val gameDuration: Int = 0,
    val totalMinionsKilled: Int = 0,
    val kills: Int = 0,
    val assists: Int = 0,
    val deaths: Int = 0,
    val teamPosition: String = "",
    val teamId: Int = 0,
    val win: Boolean = false,
    val wardsPlaced: Int = 0,
    val wardsKilled: Int = 0,
    val controlWardsPlaced: Int = 0,
    val totalDamageDealtToChampions: Int = 0,
    val item0: Int = 0,
    val item1: Int = 0,
    val item2: Int = 0,
    val item3: Int = 0,
    val item4: Int = 0,
    val item5: Int = 0,
    val item6: Int = 0,
    val championName: String = "",
    val championId: Int = 0,
    val championLevel: Int = 0,
    val name: String = "",
    val summoner1Id: Int = 0,
    val summoner2Id: Int = 0,
    val participantsPuuid: MutableList<String> = mutableListOf(),
) {
    constructor(matchId: String, queueId: String, gameDuration: Int, participantsPuuid: MutableList<String>, participant: ParticipantDto) : this(
        matchId = matchId,
        queueId = queueId,
        gameDuration = gameDuration,
        kills = participant.kills,
        assists = participant.assists,
        deaths = participant.deaths,
        teamPosition = participant.teamPosition,
        teamId = participant.teamId,
        win = participant.win,
        wardsPlaced = participant.wardsPlaced,
        wardsKilled = participant.wardsKilled,
        controlWardsPlaced = participant.challenges.controlWardsPlaced,
        item0 = participant.item0,
        item1 = participant.item1,
        item2 = participant.item2,
        item3 = participant.item3,
        item4 = participant.item4,
        item5 = participant.item5,
        item6 = participant.item6,
        championName = participant.championName,
        championId = participant.championId,
        championLevel = participant.champLevel,
        name = participant.summonerName,
        totalMinionsKilled = participant.totalMinionsKilled,
        totalDamageDealtToChampions = participant.totalDamageDealtToChampions,
        summoner1Id = participant.summoner1Id,
        summoner2Id = participant.summoner2Id,
        participantsPuuid = participantsPuuid
    )
}